### ISSUE TITLE
Language selector of aaapy doesn't work

### ISSUE THREAD

**Issue by Liikt** [Neverik/aaa-py#16]
# Bug Report

## Description

I found a small bug though. The language selector doesn't work for `x86` and `Scratch` doesn't work. 

### Steps to Reproduce

1. Go to https://aaapy.herokuapp.com
2. Click on the FFT Chapter
3. Select either `x86-64 Assembler` or `Scratch`
4. Nothing Happens

### Expected behavior

The language displayed should switch to the selected one.

## For Algorithm Archive Developers

- [x] The bug can be reproduced
- [x] The bug can be fixed (if not, please explain why not in a comment below)
- [ ] There is a timeline to fix the bug
- [ ] The bug has been fixed (Please link the PR)

**Comment by neverix** [comment]
I have successfully reproduced this bug, will try to fix it for asm.

**Comment by neverix** [comment]
ASM is working correctly now, Scratch fix left.

**Comment by neverix** [comment]
Strangely, the page renderer outputs the Julia code for Scratch.

**Comment by neverix** [comment]
This is what the current implementation does too, so I believe you should send a bug report to the upstream.
Closing.
